import 'dart:ui' as ui;

import 'package:flame/cache.dart';
import 'package:flame/components.dart';
import 'package:flame/flame.dart';
import 'package:flame/sprite.dart';
import 'package:flutter/foundation.dart';

import '../../rendering/sprite_cache.dart';

/// Centralized sprite manager that attempts to load PNG assets first,
/// falling back to procedural generation when assets are not available.
///
/// This is a singleton with lazy initialization. It bridges the existing
/// [SpriteCache] (for tile sprites) with Flame's image loading system
/// for towers, enemies, effects, and other game sprites.
///
/// Usage:
/// ```dart
/// final manager = SpriteManager.instance;
/// await manager.initialize();
///
/// final sprite = await manager.getSprite(
///   'towers/archer',
///   fallbackGenerator: (size) => _generateArcherSprite(size),
/// );
/// ```
class SpriteManager {
  // ---------------------------------------------------------------------------
  // Singleton
  // ---------------------------------------------------------------------------

  static final SpriteManager instance = SpriteManager._();
  SpriteManager._();

  // ---------------------------------------------------------------------------
  // State
  // ---------------------------------------------------------------------------

  bool _initialized = false;
  bool get isInitialized => _initialized;

  /// Cache of loaded Flame [Sprite] objects keyed by asset path (without extension).
  final Map<String, Sprite> _spriteCache = {};

  /// Cache of loaded [SpriteAnimation] objects keyed by asset key.
  final Map<String, SpriteAnimation> _animationCache = {};

  /// Cache of raw [ui.Image] objects generated by fallback generators.
  final Map<String, ui.Image> _generatedImages = {};

  /// Reference to the existing tile-level sprite cache.
  SpriteCache get tileCache => SpriteCache.instance;

  // ---------------------------------------------------------------------------
  // Initialization
  // ---------------------------------------------------------------------------

  /// Initializes the SpriteManager and ensures the underlying [SpriteCache]
  /// is ready.
  ///
  /// Safe to call multiple times; subsequent calls are no-ops.
  Future<void> initialize() async {
    if (_initialized) return;

    // Make sure the tile sprite cache is also initialized.
    if (!tileCache.isInitialized) {
      await tileCache.initialize();
    }

    _initialized = true;
  }

  // ---------------------------------------------------------------------------
  // Sprite loading
  // ---------------------------------------------------------------------------

  /// Returns a [Sprite] for the given [key].
  ///
  /// First attempts to load `assets/images/<key>.png` via Flame's image loader.
  /// If that fails (file missing, decode error, etc.), uses [fallbackGenerator]
  /// to produce a [ui.Image] procedurally.
  ///
  /// Results are cached; subsequent calls with the same [key] return instantly.
  ///
  /// [key] — logical asset name without extension, e.g. `'towers/archer'`.
  /// [fallbackGenerator] — optional function that receives a desired texture
  ///   size and returns a [ui.Image]. If null and the PNG is missing, an
  ///   empty 1x1 transparent sprite is returned.
  /// [textureSize] — desired size for the fallback generator (default 128).
  Future<Sprite> getSprite(
    String key, {
    Future<ui.Image> Function(int size)? fallbackGenerator,
    int textureSize = 128,
  }) async {
    // Return cached sprite if available.
    if (_spriteCache.containsKey(key)) {
      return _spriteCache[key]!;
    }

    // Attempt PNG load from assets.
    try {
      final image = await Flame.images.load('$key.png');
      final sprite = Sprite(image);
      _spriteCache[key] = sprite;
      return sprite;
    } catch (_) {
      // Asset not found or failed to decode — fall through to generator.
    }

    // Fallback: procedural generation.
    if (fallbackGenerator != null) {
      try {
        final image = await fallbackGenerator(textureSize);
        _generatedImages[key] = image;
        final sprite = Sprite(image);
        _spriteCache[key] = sprite;
        return sprite;
      } catch (e) {
        debugPrint('SpriteManager: fallback generator failed for "$key": $e');
      }
    }

    // Last resort: 1x1 transparent image.
    final placeholder = await _createPlaceholderImage();
    final sprite = Sprite(placeholder);
    _spriteCache[key] = sprite;
    return sprite;
  }

  // ---------------------------------------------------------------------------
  // Animation loading
  // ---------------------------------------------------------------------------

  /// Returns a [SpriteAnimation] for the given [key].
  ///
  /// Attempts to load a sprite sheet at `assets/images/<key>.png` and split it
  /// into [frameCount] frames of [textureSize] x [textureSize].
  ///
  /// If loading fails, uses [fallbackGenerator] to create individual frame
  /// images procedurally.
  ///
  /// [key] — logical asset name without extension.
  /// [frameCount] — number of frames in the animation (default 4).
  /// [stepTime] — seconds per frame (default 0.15).
  /// [textureSize] — width/height of each frame (default 128).
  /// [fallbackGenerator] — optional function that receives the frame index and
  ///   texture size, returning a [ui.Image] for that frame.
  Future<SpriteAnimation> getAnimation(
    String key, {
    int frameCount = 4,
    double stepTime = 0.15,
    int textureSize = 128,
    Future<ui.Image> Function(int frameIndex, int size)? fallbackGenerator,
  }) async {
    // Return cached animation if available.
    if (_animationCache.containsKey(key)) {
      return _animationCache[key]!;
    }

    // Attempt sprite-sheet load from assets.
    try {
      final image = await Flame.images.load('$key.png');
      final spriteSheet = SpriteSheet(
        image: image,
        srcSize: Vector2(textureSize.toDouble(), textureSize.toDouble()),
      );
      final frames = List.generate(
        frameCount,
        (i) => spriteSheet.getSprite(0, i),
      );
      final animation = SpriteAnimation.spriteList(frames, stepTime: stepTime);
      _animationCache[key] = animation;
      return animation;
    } catch (_) {
      // Asset not found — fall through to generator.
    }

    // Fallback: procedural frame generation.
    if (fallbackGenerator != null) {
      try {
        final frames = <Sprite>[];
        for (int i = 0; i < frameCount; i++) {
          final image = await fallbackGenerator(i, textureSize);
          final frameKey = '${key}_frame_$i';
          _generatedImages[frameKey] = image;
          frames.add(Sprite(image));
        }
        final animation =
            SpriteAnimation.spriteList(frames, stepTime: stepTime);
        _animationCache[key] = animation;
        return animation;
      } catch (e) {
        debugPrint(
            'SpriteManager: fallback animation generator failed for "$key": $e');
      }
    }

    // Last resort: single-frame placeholder animation.
    final placeholder = await _createPlaceholderImage();
    final animation = SpriteAnimation.spriteList(
      [Sprite(placeholder)],
      stepTime: stepTime,
    );
    _animationCache[key] = animation;
    return animation;
  }

  // ---------------------------------------------------------------------------
  // Tile sprite access (delegates to SpriteCache)
  // ---------------------------------------------------------------------------

  /// Retrieves a pre-rendered tile image from [SpriteCache].
  ///
  /// Returns null if the tile key is not found.
  ui.Image? getTile(String key) => tileCache.getTile(key);

  // ---------------------------------------------------------------------------
  // Disposal
  // ---------------------------------------------------------------------------

  /// Disposes all cached sprites, animations, and generated images.
  ///
  /// After calling this, [isInitialized] returns false and the manager
  /// must be re-initialized before use.
  void dispose() {
    _spriteCache.clear();
    _animationCache.clear();

    for (final image in _generatedImages.values) {
      image.dispose();
    }
    _generatedImages.clear();

    _initialized = false;
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  /// Creates a 1x1 transparent placeholder image.
  Future<ui.Image> _createPlaceholderImage() async {
    final recorder = ui.PictureRecorder();
    ui.Canvas(recorder); // draw nothing — transparent
    final picture = recorder.endRecording();
    final image = await picture.toImage(1, 1);
    picture.dispose();
    return image;
  }
}
